export const SET_RECIPES = "SET_RECIPES";

export const ADD_RECIPE = "ADD_RECIPE";

export const DELETE_RECIPE = "DELETE_RECIPE";

export const SET_UNSCRAPEABLES = "SET_UNSCRAPEABLES";

export const ADD_UNSCRAPEABLE = "AADD_UNSCRAPEABLE";

export const DELETE_UNSCRAPEABLE = "DELETE_UNSCRAPEABLE";

export const ADD_TO_PLANNER = "ADD_TO_PLANNER";

export const ADD_RECIPE_TO_DAY = "ADD_RECIPE_TO_DAY";

export const SET_WEEKLY_MEAL_PLAN = "SET_WEEKLY_MEAL_PLAN";

export const UPDATE_MEAL_PLAN = "UPDATE_MEAL_PLAN";
