export const SET_RECIPES = "SET_RECIPES";

export const ADD_RECIPE = "ADD_RECIPE";

export const DELETE_RECIPE = "DELETE_RECIPE";

export const SET_UNSCRAPEABLES = "SET_UNSCRAPEABLES";

export const ADD_UNSCRAPEABLE = "AADD_UNSCRAPEABLE";

export const DELETE_UNSCRAPEABLE = "DELETE_UNSCRAPEABLE";

export const ADD_TO_PLANNER = "ADD_TO_PLANNER";

export const ADD_RECIPE_TO_DAY = "ADD_RECIPE_TO_DAY";

export const REMOVE_RECIPE_FROM_DAY = "REMOVE_RECIPE_FROM_DAY";

export const SET_WEEKLY_MEAL_PLAN = "SET_WEEKLY_MEAL_PLAN";

export const UPDATE_MEAL_PLAN = "UPDATE_MEAL_PLAN";

export const SET_USER = "SET_USER";

export const REMOVE_USER = "REMOVE_USER";

export const UPDATE_RECIPE = "UPDATE_RECIPE";

export const SET_FAVOURITES = "SET_FAVOURITES";

export const UPDATE_FAVOURITE = "UPDATE_FAVOURITE";

export const SET_COLLECTIONS = "SET_COLLECTIONS";

export const ADD_COLLECTION = "ADD_COLLECTION";

export const ADD_RECIPE_TO_COLLECTION = "ADD_RECIPE_TO_COLLECTION";
